FROM python:3.12

#ARG WORKDIR=/code
#RUN mkdir $WORKDIR

RUN apt update \
 && apt install -y git \
 && apt-get install -y procps \
 && apt install -y vim \
 && apt install -y jq \
 && apt install -y curl \
 && apt clean all

WORKDIR /code

COPY . ./src/pgsync
RUN pip install --no-cache-dir -e ./src/pgsync/
